version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: keyboard-game-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - keyboard-game-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: keyboard-game-backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/keyboard-game?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - CLIENT_URL=http://localhost:3000
    networks:
      - keyboard-game-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3001 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: keyboard-game-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    networks:
      - keyboard-game-network

networks:
  keyboard-game-network:
    driver: bridge

volumes:
  mongodb_data: